#
# FFmpeg Docker, an API wrapper around FFmpeg running in a configurable docker container
# Copyright (C) 2022 Ryan McCartney
#
# This file is part of the FFmpeg Docker (ffmpeg-docker).
#
# FFmpeg Docker is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        # network_mode: "host" #Change this as required
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "false"
                DECKLINK_SDK_URL: "https://swr.cloud.blackmagicdesign.com/DeckLink/v12.4.1/Blackmagic_DeckLink_SDK_12.4.1.zip?verify="
                DECKLINK_DRIVER_URL: "https://swr.cloud.blackmagicdesign.com/DesktopVideo/v12.4.1/Blackmagic_Desktop_Video_Linux_12.4.1.tar.gz?verify="
                DECKLINK_DRIVER_VERSION: "12.4.1"
                NDI_SUPPORT: "false"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
                NON_FREE: "true"
        restart: always
        volumes:
            - ./:/home/node/app
        #devices:
        #    - /dev/blackmagic/io0:/dev/blackmagic/io0
        environment:
            NODE_ENV: "development"
            PORT: 80
            HOST: "localhost"
            WEB_GUI: "true"
            AUTH_KEY: "averysecretkey"
            AUTH_USER: admin
            AUTH_PASSWORD: admin
        ports:
            - 80:80
